// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void arcrun_Animation(lv_obj_t * TargetObject, int delay);
void movechar_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image4;
void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image8;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Panel5;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel23;
void ui_event_Chart1(lv_event_t * e);
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Panel8;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_line;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_line1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_line2;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_line3;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_line4;
extern lv_obj_t * ui_line5;
extern lv_obj_t * ui_line6;
void ui_event_Panel24(lv_event_t * e);
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel25;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
void ui_event_Panel10(lv_event_t * e);
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel12;
void ui_event_Panel14(lv_event_t * e);
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel13;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel17;
void ui_event_Panel18(lv_event_t * e);
extern lv_obj_t * ui_Panel18;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
void ui_event_Panel19(lv_event_t * e);
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
void ui_event_Panel21(lv_event_t * e);
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1932067789);    // assets/home-assistant.png
LV_IMG_DECLARE(ui_img_1007778214);    // assets/温湿度传感器 (5).png
LV_IMG_DECLARE(ui_img_603241856);    // assets/触摸屏 (1).png
LV_IMG_DECLARE(ui_img_2012228928);    // assets/1 (1).png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_1083586714);    // assets/电量 (4).png
LV_IMG_DECLARE(ui_img_13_png);    // assets/13.png
LV_IMG_DECLARE(ui_img_475179436);    // assets/5 (1).png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_8_png);    // assets/8.png
LV_IMG_DECLARE(ui_img_9_png);    // assets/9.png
LV_IMG_DECLARE(ui_img_10_png);    // assets/10.png
LV_IMG_DECLARE(ui_img_295404747);    // assets/11 (1).png
LV_IMG_DECLARE(ui_img_298894920);    // assets/12 (1).png
LV_IMG_DECLARE(ui_img_14_png);    // assets/14.png
LV_IMG_DECLARE(ui_img_297780809);    // assets/13 (1).png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
