#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX 1

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_2
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_42
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_19
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_20
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_1

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_7

#endif


#define BUILTIN_LED_GPIO            GPIO_NUM_NC
#define BOOT_BUTTON_GPIO            GPIO_NUM_0
#define TOUCH_BUTTON_GPIO           GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO     GPIO_NUM_NC


// #define DISPLAY_BACKLIGHT_PIN       GPIO_NUM_45
// #define DISPLAY_MOSI_PIN            GPIO_NUM_13
// #define DISPLAY_CLK_PIN             GPIO_NUM_48
// #define DISPLAY_DC_PIN              GPIO_NUM_21
// #define DISPLAY_RST_PIN             GPIO_NUM_NC
// #define DISPLAY_CS_PIN              GPIO_NUM_40


#define EXAMPLE_PIN_NUM_LCD_CS      GPIO_NUM_4
#define EXAMPLE_PIN_NUM_LCD_SCLK    GPIO_NUM_5
#define EXAMPLE_PIN_NUM_LCD_DATA0   GPIO_NUM_7
#define EXAMPLE_PIN_NUM_LCD_DATA1   GPIO_NUM_10
#define EXAMPLE_PIN_NUM_LCD_DATA2   GPIO_NUM_11
#define EXAMPLE_PIN_NUM_LCD_DATA3   GPIO_NUM_12
#define EXAMPLE_PIN_NUM_LCD_RST     GPIO_NUM_40

#define EXAMPLE_PIN_NUM_TOUCH_INT    GPIO_NUM_13
#define EXAMPLE_PIN_NUM_TOUCH_RST    GPIO_NUM_NC

#define TOUCH_SDA_PIN GPIO_NUM_2
#define TOUCH_SCL_PIN GPIO_NUM_1





#define DISPLAY_WIDTH   368
#define DISPLAY_HEIGHT  448
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR    true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE 0



// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_18

#endif // _BOARD_CONFIG_H_
