// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel9, 475);
    lv_obj_set_height(ui_Panel9, 315);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x232121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xF8F2F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 256, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel9, lv_color_hex(0x4E4949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel9, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel16, 209);
    lv_obj_set_height(ui_Panel16, 140);
    lv_obj_set_x(ui_Panel16, -112);
    lv_obj_set_y(ui_Panel16, -75);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel16, &ui_img_8_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel15, 209);
    lv_obj_set_height(ui_Panel15, 140);
    lv_obj_set_x(ui_Panel15, -110);
    lv_obj_set_y(ui_Panel15, 75);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel15, &ui_img_9_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel17, 209);
    lv_obj_set_height(ui_Panel17, 140);
    lv_obj_set_x(ui_Panel17, 110);
    lv_obj_set_y(ui_Panel17, 75);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel17, &ui_img_10_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_Panel18, 209);
    lv_obj_set_height(ui_Panel18, 140);
    lv_obj_set_x(ui_Panel18, 107);
    lv_obj_set_y(ui_Panel18, -77);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Panel18, &ui_img_295404747, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel18, ui_event_Panel18, LV_EVENT_ALL, NULL);

}
